export const PERMISSIONS = {
  MANAGE_SITE: 1 << 0,
  MANAGE_MEMBERS: 1 << 1,
  SUBJECT_CREATE: 1 << 2,
  SUBJECT_UPDATE: 1 << 3,
  SUBJECT_ASSIGN: 1 << 4,
  MONITORING_MANAGE: 1 << 5,
  DOCUMENT_MANAGE: 1 << 6,
  DEVIATION_MANAGE: 1 << 7,
} as const;

export const PERMISSION_FLAGS = [
  { bit: PERMISSIONS.MANAGE_SITE, label: "Manage Site" },
  { bit: PERMISSIONS.MANAGE_MEMBERS, label: "Manage Members" },
  { bit: PERMISSIONS.SUBJECT_CREATE, label: "Create Subjects" },
  { bit: PERMISSIONS.SUBJECT_UPDATE, label: "Update Subjects" },
  { bit: PERMISSIONS.SUBJECT_ASSIGN, label: "Assign Subjects" },
  { bit: PERMISSIONS.MONITORING_MANAGE, label: "Manage Monitoring" },
  { bit: PERMISSIONS.DOCUMENT_MANAGE, label: "Manage Documents" },
  { bit: PERMISSIONS.DEVIATION_MANAGE, label: "Manage Deviations" },
] as const;

export const SITE_ROLE_DEFAULT_MASK: Record<string, number> = {
  owner:
    PERMISSIONS.MANAGE_SITE |
    PERMISSIONS.MANAGE_MEMBERS |
    PERMISSIONS.SUBJECT_CREATE |
    PERMISSIONS.SUBJECT_UPDATE |
    PERMISSIONS.SUBJECT_ASSIGN |
    PERMISSIONS.MONITORING_MANAGE |
    PERMISSIONS.DOCUMENT_MANAGE |
    PERMISSIONS.DEVIATION_MANAGE,
  admin:
    PERMISSIONS.MANAGE_SITE |
    PERMISSIONS.MANAGE_MEMBERS |
    PERMISSIONS.SUBJECT_CREATE |
    PERMISSIONS.SUBJECT_UPDATE |
    PERMISSIONS.SUBJECT_ASSIGN |
    PERMISSIONS.MONITORING_MANAGE |
    PERMISSIONS.DOCUMENT_MANAGE |
    PERMISSIONS.DEVIATION_MANAGE,
  coordinator:
    PERMISSIONS.SUBJECT_CREATE |
    PERMISSIONS.SUBJECT_UPDATE |
    PERMISSIONS.SUBJECT_ASSIGN |
    PERMISSIONS.DOCUMENT_MANAGE,
  nurse:
    PERMISSIONS.SUBJECT_CREATE | PERMISSIONS.SUBJECT_UPDATE | PERMISSIONS.SUBJECT_ASSIGN,
  investigator:
    PERMISSIONS.SUBJECT_UPDATE | PERMISSIONS.SUBJECT_ASSIGN | PERMISSIONS.DEVIATION_MANAGE,
  viewer: 0,
};

export const SITE_MEMBER_ROLES = ["owner", "admin", "coordinator", "nurse", "investigator", "viewer"] as const;

export type SiteMemberRole = (typeof SITE_MEMBER_ROLES)[number];
